### ISSUE TITLE
Homebrew complain SHA256 mismatch

### ISSUE THREAD

**Issue by erongd** [cloudfoundry/homebrew-tap#13]
==> Installing cf-cli from cloudfoundry/tap
==> Downloading https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.20.0&source=homebrew
==> Downloading from https://s3.amazonaws.com/go-cli/releases/v6.20.0/cf-cli_6.20.0_osx.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 4cce2563a3f4f33dc877f6b3a41ba452a96c43b5dbf7a03c3a245152ae41239b
Actual: f668f90a378c9775a7d7772955daee206b6956c8d34ab47f574832592e8a2d81
Archive: /Users/erong/Library/Caches/Homebrew/cf-cli-6.20.0.0&source=homebrew
To retry an incomplete download, remove the file above.

**Comment by krishicks** [comment]
Closing as #14 fixes the issue.
