### ISSUE TITLE
Homebrew Error: SHA256 mismatch

### ISSUE THREAD

**Issue by emmabeynon** [cloudfoundry/homebrew-tap#17]
Hi,
I'm running `brew upgrade` and getting the below error:
```
==> Upgrading cloudfoundry/tap/cf-cli
==> Downloading https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.21.1&source=homeb
Already downloaded: /Users/emmabeynon/Library/Caches/Homebrew/cf-cli-6.21.1.1&source=homebrew
Error: SHA256 mismatch
Expected: 0faca62b5983260a371a08af8c5cb73d66ca324da16a4225789f2a479107ff18
Actual: 862701337dc3892382dea2b1f6a92ad4cf2baadb464dec0a81e982bfe8b2f793
Archive: /Users/emmabeynon/Library/Caches/Homebrew/cf-cli-6.21.1.1&source=homebrew
To retry an incomplete download, remove the file above.
```

I've seen similar issues be raised here, but can't see if there's something I need to do on my end to get this fixed?

Thanks,
Emma

**Comment by voelzmo** [comment]
Yup, looking at [the commits for the formula](https://github.com/cloudfoundry/homebrew-tap/commits/master/cf-cli.rb) you can see that some build seems to publish new `sha`s for already existing version numbers. This [has](https://github.com/cloudfoundry/homebrew-tap/issues/9) [happened](https://github.com/cloudfoundry/homebrew-tap/issues/13) [before](https://github.com/cloudfoundry/homebrew-tap/issues/3), so I'd really like to see this fixed.

**Comment by GarfieldIsAPhilosopher** [comment]
we have fixed the problem with the commits, please run the following commands for update
```
brew cleanup
brew tap cloudfoundry/tap update
```

Moreover we also fixed the process issue that was causing this to happen repeatedly. We do not expect these to pop up again.

**Comment by emmabeynon** [comment]
That works - thanks very much!
