### ISSUE TITLE
bosh-cli should include an option to install as `bosh`

### ISSUE THREAD

**Issue by aramprice** [cloudfoundry/homebrew-tap#27]
https://github.com/cloudfoundry/homebrew-tap/commit/118002558466fc391bbd7488a0df55a4986b45a1#diff-2c517ca70f8aa8d0bd040218ae797623 introduced a change to the `bosh-cli` installation to allow the it to exist alongside the ruby cli.

For people using only the new CLI it should be possible to install the executable as `bosh`.

**Comment by cppforlife** [comment]
@wendorf thoughts?

**Comment by wendorf** [comment]
This makes sense. Homebrew standards suggest having every option prefix with "with" or "without" (https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#adding-optional-steps), so this could be "--with-bosh-binary-name" or something similar. Then `binary_name = build.with?("bosh-binary-name") ? "bosh" : "gosh"`

**Comment by aramprice** [comment]
Woot! When does this land in home-brew?

**Comment by wendorf** [comment]
When the next version of the CLI (v0.0.152) is cut, the pipeline will auto-bump the formula with the new change.

**Comment by dpb587-pivotal** [comment]
Closing - landed at a6f12da3535a67ed83a5d754445f33bed0f382e7.
