### ISSUE TITLE
install BOSH as "bosh", not "bosh2"

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/homebrew-tap#32]
Now that BOSH 2.0 is the binary linked to by the documentation, are we considering renaming the alias for new users?

**Comment by dpb587-pivotal** [comment]
@cppforlife can we consider installing as `bosh` now?

**Comment by albertoaflores** [comment]
+1

**Comment by sslavic** [comment]
This seems to have been fixed in 2.0.31 (see https://github.com/cloudfoundry/homebrew-tap/commit/c5676cdf727f748f7bda2e513343246cb828c14b#diff-2c517ca70f8aa8d0bd040218ae797623)
