### ISSUE TITLE
fatal: repository 'https://github.com/sthulb/mime.git/' not found

### ISSUE THREAD

**Issue by timtclark** [cloudfoundry/homebrew-tap#35]

**Comment by markstokan** [comment]
Hi Tim.

Thanks for filing this issue.  Do you remember which app you were installing from this tap that produced this error?

I suspect there is a go program provided by the tap that is referencing a third party repo that has been deleted but my initial pass did not show any references to:

'https://github.com/sthulb/mime.git/'

**Comment by timtclark** [comment]
Cloud foundry

**Comment by dkoper** [comment]
@timtclark Can you provide the full output, including the command as you ran it?

**Comment by dkoper** [comment]
Closing. We're guessing there was something wrong in your local environment or the message came from somewhere else. Without more information there's nothing we can investigate.
Feel free to re-open or submit a new issue if it happens again and you can share the full command terminal output.
