### ISSUE TITLE
Brew Upgrade Fails

### ISSUE THREAD

**Issue by AlexMcConnell** [cloudfoundry/homebrew-tap#39]
==> Upgrading 1 outdated package, with result:
cloudfoundry/tap/bbl v4.2.1
==> Upgrading cloudfoundry/tap/bbl
==> Downloading https://github.com/cloudfoundry/bosh-bootloader/releases/downloa

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "bbl"
Download failed: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v4.2.1/bbl-v4.2.1_osx

**Comment by genevievelesperance** [comment]
Fixed in https://github.com/cloudfoundry/homebrew-tap/commit/c2ac18457ec7350bed7aefa513be856c53556a36
